title: "Gruppo Atlas — SWE 2025/2026"
description: "Sito del progetto di Ingegneria del Software del gruppo Atlas (PD1, Università di Padova)"
baseurl: "/Sitoesempioswe"  # ⚠️ es. "/atlas-site" oppure "/Sitoesempioswe"
url: "https://riccardovalerio.github.io"  # es. "https://riccardovalerio.github.io"

markdown: kramdown
highlighter: rouge
theme: null

exclude:
  - README.md
  - .github/
  - Gemfile
  - Gemfile.lock
